export type ErrorCode =
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "VALIDATION_ERROR"
  | "CONFLICT"
  | "ACTIVATION_CODE_INVALID"
  | "ACTIVATION_CODE_USED"
  | "ACTIVATION_CODE_EXPIRED"
  | "ACCOUNT_DISABLED"
  | "RATE_LIMITED"
  | "INTERNAL_ERROR"
  | "BASE_SCOPE_INVALID"
  | "CONTROL_EXPIRED"
  | "REVISION_EXPIRED"
  | "CONTENT_INCOMPATIBLE"
  | "RESOURCE_INSUFFICIENT"
  | "SITE_OCCUPIED"
  | "REQUIREMENTS_NOT_MET"
  | "BUDGET_EXCEEDED"
  | "IDEMPOTENCY_CONFLICT"
  | "DEVICE_BUSY"
  | "CAPABILITY_UNAVAILABLE";

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
  };
}
